/** Every page of the new site, for the route, content and accessibility suites. */
export const PAGES = [
  '/',
  '/websites',
  '/systems',
  '/care',
  '/work',
  '/approach',
  '/pricing',
  '/start',
  '/resources',
  '/resources?category=glossary',
  '/resources/how-to-brief-a-web-design-agency',
  '/resources/more-enquiries-from-your-website',
  '/resources/nextjs-vs-wordpress',
  '/resources/small-business-website-checklist',
  '/resources/tech-solutions-for-small-businesses',
  '/resources/website-care-plans',
  '/resources/website-cost-uk',
  '/resources/website-design-for-cics',
  '/resources/what-is-virtual-marketing',
  '/web-design-preston',
  '/trades',
  '/repair-and-retail',
  '/clinics',
  '/professional-services',
  '/brand',
  '/privacy-policy',
  '/terms',
  '/industries/community-interest-companies',
  '/lifestyle-venues',
  '/work/frozen-computers',
] as const
