"""
Build the wordmark and monogram SVGs, and the path module the site renders.

Run once, from the repository root, after any change to the outline settings:

    python3 -I scripts/brand/build_logo.py

Writes:
    public/brand/masuyo-wordmark-petrol.svg
    public/brand/masuyo-wordmark-paper-aqua-dot.svg
    public/brand/masuyo-monogram-petrol.svg
    public/brand/masuyo-monogram-mist.svg
    public/brand/masuyo-monogram-aqua.svg
    lib/brand/logo-paths.ts

Geometry is taken from the brand guidelines PDF rather than chosen by eye:

- The wordmark is Albert Sans Extra Bold with the font's own kerning and minus
  4% tracking. Measured on the cover, every glyph sits 0.04 em further left than
  the font alone would put it, linearly, which is the display tracking.
- The monogram tile was measured from a 600 dpi render of page 3. For a tile of
  side T: glyph size 0.634 T, the m starts 0.192 T from the left, the baseline
  sits 0.718 T from the top, and the corner radius is 0.09 T.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from outline_text import outline  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "public" / "brand"
TS = ROOT / "lib" / "brand" / "logo-paths.ts"

PETROL = "#0F3B4F"
PAPER = "#F3F6F7"
AQUA = "#4FE0E6"
MIST = "#E4EAEC"

# Monogram tile proportions, from page 3 of the guide.
TILE = 1000
GLYPH_SCALE = 0.634          # font size as a fraction of the tile side
M_LEFT = 0.192               # left edge of the m ink
BASELINE = 0.718             # baseline from the top
RADIUS = 0.09                # corner radius


def fmt(n: float) -> str:
    return f"{n:.2f}".rstrip("0").rstrip(".")


def wordmark_svg(data: dict, letters: str, dot: str, title: str) -> str:
    x0, y0, x1, y1 = data["ink"]
    w, h = x1 - x0, y1 - y0
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{fmt(x0)} {fmt(y0)} {fmt(w)} {fmt(h)}" '
        f'width="{fmt(w)}" height="{fmt(h)}" role="img" aria-label="{title}">'
        f"<title>{title}</title>"
        f'<path fill="{letters}" d="{data["letters"]}"/>'
        f'<path fill="{dot}" d="{data["dot"]}"/>'
        "</svg>\n"
    )


def monogram_transform(data: dict) -> tuple[float, float, float]:
    s = GLYPH_SCALE * TILE / data["unitsPerEm"]
    m_ink_left = data["lettersInk"][0]
    tx = M_LEFT * TILE - m_ink_left * s
    ty = BASELINE * TILE
    return s, tx, ty


def monogram_svg(data: dict, tile: str, letters: str, dot: str) -> str:
    s, tx, ty = monogram_transform(data)
    r = RADIUS * TILE
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {TILE} {TILE}" '
        f'width="{TILE}" height="{TILE}" role="img" aria-label="Masuyo">'
        "<title>Masuyo</title>"
        f'<rect width="{TILE}" height="{TILE}" rx="{fmt(r)}" fill="{tile}"/>'
        f'<g transform="translate({fmt(tx)} {fmt(ty)}) scale({s:.4f})">'
        f'<path fill="{letters}" d="{data["letters"]}"/>'
        f'<path fill="{dot}" d="{data["dot"]}"/>'
        "</g></svg>\n"
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    TS.parent.mkdir(parents=True, exist_ok=True)

    word = outline("masuyo.")
    mono = outline("m.")

    files = {
        "masuyo-wordmark-petrol.svg": wordmark_svg(word, PETROL, PETROL, "Masuyo"),
        "masuyo-wordmark-paper-aqua-dot.svg": wordmark_svg(word, PAPER, AQUA, "Masuyo"),
        "masuyo-monogram-petrol.svg": monogram_svg(mono, PETROL, PAPER, AQUA),
        "masuyo-monogram-mist.svg": monogram_svg(mono, MIST, PETROL, PETROL),
        "masuyo-monogram-aqua.svg": monogram_svg(mono, AQUA, PETROL, PETROL),
    }
    for name, svg in files.items():
        (OUT / name).write_text(svg)

    x0, y0, x1, y1 = word["ink"]
    s, tx, ty = monogram_transform(mono)
    o_height = word["oHeight"]
    module = f"""/**
 * Wordmark and monogram geometry.
 *
 * Generated by scripts/brand/build_logo.py from Albert Sans Extra Bold, so the
 * logo needs no font to render. Do not edit by hand: change the script and run
 * it again, so the files in public/brand and this module stay identical.
 */

export const WORDMARK = {{
  viewBox: '{fmt(x0)} {fmt(y0)} {fmt(x1 - x0)} {fmt(y1 - y0)}',
  width: {fmt(x1 - x0)},
  height: {fmt(y1 - y0)},
  /** Height of the lowercase o, the clear space unit, in the same units. */
  oHeight: {fmt(o_height)},
  letters: {json.dumps(word["letters"])},
  dot: {json.dumps(word["dot"])},
}} as const

export const MONOGRAM = {{
  size: {TILE},
  radius: {fmt(RADIUS * TILE)},
  transform: 'translate({fmt(tx)} {fmt(ty)}) scale({s:.4f})',
  letters: {json.dumps(mono["letters"])},
  dot: {json.dumps(mono["dot"])},
}} as const
"""
    TS.write_text(module)
    print("wrote", ", ".join(files), "and", TS.relative_to(ROOT))


if __name__ == "__main__":
    main()
