/**
 * The glossary, as a chip within Resources rather than a page of its own: an
 * A to Z list, each term a short definition and, where one exists, a link to
 * the article that explains it best. Terms are in sentence case; product and
 * brand names keep their own capitals.
 */

export interface GlossaryTerm {
  term: string
  definition: string
  /** The article that explains the term best, when there is one. */
  slug?: string
}

export const GLOSSARY: GlossaryTerm[] = [
  {"term": "A/B testing", "definition": "A method of comparing two versions of a webpage or ad to see which performs better. One group of users sees version A, another sees version B, and you measure which achieves your goal: more clicks, sign-ups, or purchases."},
  {"term": "Alt text", "definition": "A written description added to an image on a webpage. It helps search engines understand what an image shows, and is read aloud by screen readers for visually impaired users. Missing alt text is both an SEO and accessibility issue."},
  {"term": "Backlink", "definition": "A link from another website to yours. Search engines treat backlinks as votes of confidence: the more high-quality sites that link to you, the more authority your site tends to have in search rankings."},
  {"term": "Bounce rate", "definition": "The percentage of visitors who land on a page and leave without clicking anything else. A high bounce rate is not always bad (it depends on the page purpose), but on key landing pages it often signals a mismatch between what people expect and what they find."},
  {"term": "Call to action (CTA)", "definition": "A button, link, or prompt that tells a visitor what to do next. Examples include \"Get a free quote\", \"Book a call\", or \"Download the guide\". A clear CTA is one of the simplest ways to improve conversion rates."},
  {"term": "Canonical URL", "definition": "The preferred version of a webpage when multiple URLs show the same or similar content. A canonical tag tells search engines which version to index, preventing duplicate content issues that can dilute your rankings."},
  {"term": "Click-through rate (CTR)", "definition": "The percentage of people who click on a link after seeing it. Used in search results (how many people click your listing vs see it) and in email marketing (how many recipients click a link in your email)."},
  {"term": "Content management system (CMS)", "definition": "Software that lets you create and manage website content without writing code. WordPress, Sanity, and Contentful are popular examples. A CMS allows business owners to update text and images themselves after a site is built.", "slug": "nextjs-vs-wordpress"},
  {"term": "Conversion", "definition": "When a visitor completes a desired action on your website. A conversion could be making a purchase, submitting an enquiry form, signing up for a newsletter, or calling your phone number, depending on whatever goal the page is designed around.", "slug": "more-enquiries-from-your-website"},
  {"term": "Conversion rate", "definition": "The percentage of visitors who complete a desired action. If 200 people visit your contact page and 14 fill in the form, your conversion rate is 7%. Improving conversion rate is often more cost-effective than driving more traffic.", "slug": "more-enquiries-from-your-website"},
  {"term": "Core Web Vitals", "definition": "A set of three Google metrics that measure real-world user experience: Largest Contentful Paint (how fast the main content loads), Interaction to Next Paint (how quickly the page responds to interaction), and Cumulative Layout Shift (how stable the layout is while loading). These directly affect Google rankings."},
  {"term": "Cost per click (CPC)", "definition": "The amount you pay each time someone clicks on one of your paid ads. Used in Google Ads and Meta Ads. A lower CPC means you are paying less to get traffic, but the quality of that traffic also matters."},
  {"term": "Cost per lead (CPL)", "definition": "The total spend divided by the number of leads generated. If you spend £500 on ads and get 25 enquiries, your CPL is £20. This is a more meaningful metric than CPC because it tracks actual business outcomes, not just clicks."},
  {"term": "Domain Authority (DA)", "definition": "A score (1 to 100) developed by Moz that predicts how likely a website is to rank in search results. It is based on the number and quality of backlinks pointing to the site. DA is a useful benchmark, but not a metric Google itself uses."},
  {"term": "Favicon", "definition": "The small icon that appears in a browser tab next to a page title, and in bookmarks. Usually a simplified version of your logo. A missing favicon is a small detail that makes a site look less polished."},
  {"term": "Google Business Profile (GBP)", "definition": "The free listing that appears in Google Maps and in the local pack of search results. For businesses serving a local area, a fully optimised GBP is often the fastest route to more enquiries, often more impactful than the main website for many local searches."},
  {"term": "Heading tags (H1, H2, H3)", "definition": "HTML elements that structure content on a page. The H1 is the main heading, and there should only be one per page. H2s and H3s are sub-headings. Search engines use these to understand page structure, so using them logically matters for SEO.", "slug": "small-business-website-checklist"},
  {"term": "Heatmap", "definition": "A visual tool that shows where users click, scroll to, or move their mouse on a webpage. Tools like Hotjar generate heatmaps. They are useful for understanding which parts of a page people engage with and where they drop off."},
  {"term": "Impression", "definition": "The number of times an ad or search result is shown, regardless of whether anyone clicked it. Impressions measure visibility. A high impression count with a low CTR suggests your headline or listing is not compelling enough."},
  {"term": "Keyword", "definition": "A word or phrase that people type into search engines. SEO involves targeting the keywords your ideal customers use, both to optimise your existing pages and to guide what content to create."},
  {"term": "Landing page", "definition": "A standalone webpage designed around a single goal, usually to capture a lead or make a sale. Unlike a standard homepage, a landing page removes distractions and focuses the visitor on one action. Often used in paid advertising campaigns."},
  {"term": "Meta description", "definition": "The short summary that appears under your page title in search results. It does not directly affect rankings, but a well-written meta description improves click-through rate by telling searchers exactly what they will find on the page."},
  {"term": "Organic traffic", "definition": "Visitors who arrive at your website from unpaid search results. As opposed to paid traffic from ads. Organic traffic is the goal of SEO, building a sustainable source of visitors that does not require ongoing ad spend.", "slug": "what-is-virtual-marketing"},
  {"term": "Page speed", "definition": "How quickly a webpage loads. Measured in seconds. Google uses page speed as a ranking signal, and slow pages lose visitors.", "slug": "nextjs-vs-wordpress"},
  {"term": "Responsive design", "definition": "A web design approach where a site automatically adjusts its layout to fit any screen size: phone, tablet, or desktop. Responsive design is the standard, not a premium feature. Google also uses mobile-first indexing, meaning how your site performs on mobile affects your overall rankings.", "slug": "small-business-website-checklist"},
  {"term": "Return on ad spend (ROAS)", "definition": "Revenue generated for every pound spent on advertising. If you spend £1,000 on ads and generate £4,000 in revenue, your ROAS is 4x (or 400%). It is a core metric for judging whether a paid campaign is profitable."},
  {"term": "Schema markup", "definition": "Code added to a webpage that helps search engines understand the content in detail, for example by flagging that a page contains a product with a price, a review with a star rating, or an event with a date. Can lead to rich results in Google that stand out from standard listings.", "slug": "small-business-website-checklist"},
  {"term": "Search engine optimisation (SEO)", "definition": "The process of improving a website so it ranks higher in search engine results for relevant queries. SEO covers three areas: technical (how the site is built), on-page (the content and structure), and off-page (backlinks and authority). Results take months to materialise but compound over time.", "slug": "what-is-virtual-marketing"},
  {"term": "SSL certificate", "definition": "A security certificate that encrypts the connection between a website and its visitors. Sites with SSL show \"https://\" and a padlock icon in the browser. Google treats SSL as a ranking factor, and modern browsers warn users when a site does not have one.", "slug": "website-care-plans"},
  {"term": "Title tag", "definition": "The clickable headline that appears in search results and in the browser tab. One of the most important on-page SEO elements. Each page should have a unique, descriptive title tag under 60 characters that includes the target keyword."},
  {"term": "UX (user experience)", "definition": "How easy and enjoyable a website or app is to use. Good UX means visitors can find what they need quickly, the layout makes sense, and nothing feels confusing or broken. Poor UX drives visitors away regardless of how good your product or service is."},
  {"term": "XML sitemap", "definition": "A file that lists all the important pages on your website and helps search engines discover and index them. Submitting a sitemap to Google Search Console is one of the first steps in any SEO setup.", "slug": "nextjs-vs-wordpress"},
]
